tubes
=====

        a series of tubes


tubes is a library that allows you creating web applications by composing little
functions using the `pipe library <http://github.com/marianoguerra/pipe>`_
to check or mutate the request along the way.

tubes make it easy to test each functionality in isolation or on blocks at
different levels by using pipe's compose functionality.

install
-------

go to clojars for instructions:

https://clojars.org/org.marianoguerra/tubes

license
-------

Copyright (C) 2013 Mariano Guerra

Distributed under the Eclipse Public License, the same as Clojure.
